#!/bin/bash
# My first script

#  Compilers: -std=c++11 or -std=gnu++11


custom="/home/shomeb/f/fredjoha/Desktop/master-code/MRST/mrst-core/examples/data/tmp/basis_custom/input/"
hetro="/home/shomeb/f/fredjoha/Desktop/master-code/MRST/mrst-core/examples/data/tmp/basis_hetero/input/"
big="/home/shomeb/f/fredjoha/Desktop/master-code/MRST/mrst-core/examples/data/tmp/basis_big/input/"

FN=$custom
            
echo "Compiling Code!"
make
echo "Running Code!"
mpirun -n 1 ./main $FN
mpirun -n 2 ./main $FN
mpirun -n 3 ./main $FN
mpirun -n 4 ./main $FN
#$mpirun -hostfile my_hostfile  ./main $FN
#mpirun -n 5 ./main $FN
#mpirun -n 6 ./main $FN
#mpirun -n 7 ./main $FN
#mpirun -n 8 ./main $FN
#mpirun -n 9 ./main $FN
#mpirun -n 10 ./main $FN



# delete all test-problems:
# rm -rf /home/shomeb/f/fredjoha/Desktop/master-code/MRST/mrst-core/examples/data/tmp/
