#!/bin/bash
# My first script

#  Compilers: -std=c++11 or -std=gnu++11


spe10="/home/shomeb/f/fredjoha/Desktop/master-code/checkout-mrst/mrst-bitbucket/mrst-core/examples/data/tmp/basis_spe10/"


rm main

make           
./main $spe10







#mpirun -n 1  ./cmakedir/main $spe10
#mpirun -n 2 ./cmakedir/main $spe10
#mpirun -n 3 ./cmakedir/main $spe10
#mpirun -n 4 ./cmakedir/main $spe10

